apiVersion: v1
kind: PersistentVolume
metadata:
  name: micropv
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: "/home/bola/Documents/risf/microitsf"
